version: '3'
services:
  ##################################################################################################
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  ##################################################################################################
  api:
    build: "./api"
    ports:
      - "8081:8081"
    restart: always
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://mongodb:27017/glens-backend
  ##################################################################################################
  mongodb:
    image:  "mongo"
  ##################################################################################################
  appstud-face-detection:
    depends_on:
      - redis
    restart: always
    build: "./worker/face-detection-worker"
    volumes:
      - './worker/face-detection-worker:/app'
